SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) 
IN (SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC;
-- GROUP BY로 묶으면 가장 상단에 있는 데이터들을 임의로 가져옴
-- 서브쿼리로 최대값을 따로 찾아줌